//
//  main.swift
//  StringsTranslator
//
//  Created by Derek Maurer on 7/11/14.
//  Copyright (c) 2014 Moca Apps. All rights reserved.
//

import Foundation

/////////////////////////////////////////
////////// VARIABLES TO SET /////////////
/////////////////////////////////////////
let originalStringsFilePath = "/Users/derekmaurer/Dropbox/development/Projects/AppStore/Search Emoji/Search Emoji/en.lproj/Localizable.strings"
let outputPath = "/Users/derekmaurer/Desktop/languages"
let originalStringsLanguage = "en" //English
let microsoftTranslatorClientSecret = "FpzdmPQtvjwNxI8PRgejCp5gBeI4Og/3tAGUQ/tXdFA="
let microsoftTranslatorAppID = "SearchEmoji"
/////////////////////////////////////////
/////////////////////////////////////////
/////////////////////////////////////////

let rootAPIURL = "http://api.microsofttranslator.com/v2/Http.svc/Translate?"
var languages = ["en":"English",
    "ar":"Arabic",
    "bg":"Bulgarian",
    "ca":"Catalan",
    "zh-CHS":"Chinese Simplified",
    "cs":"Czech",
    "da":"Danish",
    "nl":"Dutch",
    "et":"Estonian",
    "fi":"Finnish",
    "fr":"French",
    "de":"German",
    "el":"Greek",
    "ht":"Haitian Creole",
    "hi":"Hindi",
    "hu":"Hungarian",
    "id":"Indonesian",
    "it":"Italian",
    "ja":"Japanese",
    "ko":"Korean",
    "lv":"Latvian",
    "lt":"Lithuanian",
    "ms":"Malay",
    "mt":"Maltese",
    "no":"Norwegian",
    "fa":"Persian",
    "pl":"Polish",
    "pt":"Portuguese",
    "ro":"Romanian",
    "ru":"Russian",
    "sk":"Slovak",
    "sl":"Slovenian",
    "es":"Spanish",
    "sv":"Swedish",
    "th":"Thai",
    "tr":"Turkish",
    "uk":"Ukrainian",
    "ur":"Urdu",
    "vi":"Vietnamese",
    "cy":"Welsh"]

/////////////////////////////////////////////////////////
//Setup access token
/////////////////////////////////////////////////////////

AccessToken.setAppID(microsoftTranslatorAppID)
AccessToken.setClientSecret(microsoftTranslatorClientSecret)

/////////////////////////////////////////////////////////
//Remove the selected language
/////////////////////////////////////////////////////////

languages[originalStringsLanguage] = nil

/////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////
//Check if all the files exist and load
/////////////////////////////////////////////////////////

if !NSFileManager.defaultManager().fileExistsAtPath(originalStringsFilePath) {
    println("Failed to start translating file because there wasn't a file at path: \(originalStringsFilePath)")
    exit(0)
}

let stringsFileData = NSString(contentsOfFile: originalStringsFilePath, encoding: NSUTF8StringEncoding, error: nil)

if stringsFileData.length <= 0 {
    println("Failed to parse the strings file because it didn't have any content")
    exit(0)
}

let strings = stringsFileData.stringByReplacingOccurrencesOfString(" ", withString: "").componentsSeparatedByString("\n") as [NSString]

/////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////
// Start the translation and write to appropriate files
/////////////////////////////////////////////////////////

if let accessToken = AccessToken.accessToken() {
    for line in strings {
        if line.rangeOfString("\"").location != NSNotFound {
            var key = (line.componentsSeparatedByString("=")[0] as NSString).stringByReplacingOccurrencesOfString("\"", withString: "")
            var value = (line.componentsSeparatedByString("=")[0] as NSString).stringByReplacingOccurrencesOfString("\"", withString: "")
            
            for (languageCode:String, languageName:String) in languages {
                //let translatedString = translateStringSynchronously(value, originalStringsLanguage, languageCode)
                
                let translatedString = value
                
                var fileText = ""
                let filePath = "\(outputPath)/\(languageCode).lproj/Localizable.strings"
                let directoryPath = "\(outputPath)/\(languageCode).lproj"
                
                if !NSFileManager.defaultManager().fileExistsAtPath("directoryPath") {
                    NSFileManager.defaultManager().createDirectoryAtPath(directoryPath, withIntermediateDirectories: true, attributes: nil, error: nil)
                }
                
                if NSFileManager.defaultManager().fileExistsAtPath(filePath) {
                    fileText = NSString(contentsOfFile: filePath, encoding: NSUTF8StringEncoding, error: nil)
                }
                else {
                    fileText = "/*\nFile generated by StringsTranslator. http://mocaapps.com \nLanguage: \(languageName)\n*/\n\n"
                }
                
                fileText += "\n\"\(key)\" = \"\(translatedString)\""
                
                fileText.writeToFile(filePath, atomically: true, encoding: NSUTF8StringEncoding, error: nil)
            }
        }
    }
}
else {
    println("Failed to get the accesstoken for microsoft translator")
}

/////////////////////////////////////////////////////////